//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrain
    {
        public int Id { get; set; }
        public string trainname { get; set; }
        public string trainno { get; set; }
        public System.DateTime departure { get; set; }
        public string destination { get; set; }
    }
}
